---
apiVersion: v1
kind: Pod
metadata:
  name: node-debugger-0
  namespace: fd-dev-leopold
spec:
  containers:
    - image: europe-west3-docker.pkg.dev/monogon-infra/fd-dev/fd-k8s-demo:latest
      imagePullPolicy: Always
      name: debugger
      command:
        - /bin/bash
      securityContext:
        privileged: true
      stdin: true
      tty: true
  hostNetwork: true
  hostPID: true
  hostIPC: true
  nodeName: metropolis-3d7de37302e89f6b4bf9a1ccad438d73
