---
apiVersion: v1
kind: Pod
metadata:
  name: node-fd-debug-0
spec:
  containers:
    - image: europe-west3-docker.pkg.dev/monogon-infra/fd-dev/fd-k8s-demo:latest
      imagePullPolicy: Always
      name: debugger
      command:
        - /bin/bash
      securityContext:
        privileged: true
      stdin: true
      tty: true
  hostNetwork: true
  nodeName: metropolis-078e9c92e3a53a784fd8d0ddcf0f5a5e
